"""changed long and lat from float to numeric

Revision ID: 4a3e82dccaca
Revises: fe2369c2eab9
Create Date: 2018-03-16 17:29:17.088727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3e82dccaca'
down_revision = 'fe2369c2eab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_data',
    sa.Column('time', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(length=70), nullable=False),
    sa.Column('totalBikeStands', sa.Integer(), nullable=True),
    sa.Column('availableBikeStands', sa.Integer(), nullable=True),
    sa.Column('availableBikes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('time', 'address')
    )
    op.create_table('static_data',
    sa.Column('address', sa.String(length=70), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('banking', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('address'),
    sa.UniqueConstraint('address')
    )
    op.create_table('weather_data',
    sa.Column('time', sa.BigInteger(), nullable=False),
    sa.Column('mainDescription', sa.String(length=70), nullable=True),
    sa.Column('detailedDescription', sa.String(length=70), nullable=True),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.Column('currentTemp', sa.Float(), nullable=True),
    sa.Column('maxTemp', sa.Float(), nullable=True),
    sa.Column('minTemp', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('windSpeed', sa.Float(), nullable=True),
    sa.Column('windAngle', sa.Integer(), nullable=True),
    sa.Column('cloudDensity', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('time'),
    sa.UniqueConstraint('time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data')
    op.drop_table('static_data')
    op.drop_table('dynamic_data')
    # ### end Alembic commands ###
