"""users, weather, static, dynamic

Revision ID: f40b958d51b8
Revises: 
Create Date: 2018-03-16 15:14:45.626153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40b958d51b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
    sa.Column('time', sa.BigInteger(), nullable=False),
    sa.Column('mainDescription', sa.String(length=70), nullable=True),
    sa.Column('detailedDescription', sa.String(length=70), nullable=True),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.Column('currentTemp', sa.Float(), nullable=True),
    sa.Column('maxTemp', sa.Float(), nullable=True),
    sa.Column('minTemp', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('windSpeed', sa.Float(), nullable=True),
    sa.Column('windAngle', sa.Integer(), nullable=True),
    sa.Column('cloudDensity', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('time'),
    sa.UniqueConstraint('time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data')
    # ### end Alembic commands ###
